title: Pu Tan
logo: /Github_img/IMG_7936.JPG
description: Passionate Data Scientist with a Master's degree in Data Science from University of Pennsylvania. Adept at leveraging Python, SQL, and advanced machine learning techniques to turn data into actionable insights. Known for a proactive approach and an eagerness to dive into challenging data puzzles and make a tangible impact in data-driven decision-making.
show_downloads: false
theme: jekyll-theme-minimal
